# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# source 'https://github.com/CocoaPods/Specs.git'

target 'IGListKitLearnSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IGListKitLearnSwift
    pod 'IGListKit', '~> 3.4.0'
    pod 'SnapKit', '~> 5.0.1'
    

end
